### ISSUE TITLE
Publish it on Modrith?

### ISSUE THREAD

**Issue by SaiBot-YT** [Sorenon/MCXR#25]
could you please publish your mod on modrith? its wayy easier for the end user to
https://modrinth.com/?
seach and combine a modpack

**Comment by Fishvap** [comment]
It's two platforms to maintain. Is there a way to upload to both platforms at the same time, using a tool?

**Comment by Sorenon** [comment]
The only reason MCXR isn't on modrinth / curseforge yet is because i still feel its not ready for that kind of an audience. However thats not for much longer as the work I'm doing in the [refactor branch](https://github.com/Sorenon/MCXR/tree/refactor)  should deal with all the major issues (apart from teleportation and rebinding).

In the meantime I'll leave this issue open until the mods have been published.

**Comment by SaiBot-YT** [comment]
ahh.. oke. when i found the mod i thought of myself being dumb not finding it  earlier... but Thanks to Sidequest using MCXR will be more known anyway

**Comment by Flamgop** [comment]
> The only reason MCXR isn't on modrinth / curseforge yet is because i still feel its not ready for that kind of an audience. However thats not for much longer as the work I'm doing in the [refactor branch](https://github.com/Sorenon/MCXR/tree/refactor) should deal with all the major issues (apart from teleportation and rebinding).
> 
> In the meantime I'll leave this issue open until the mods have been published.

I think QCXR team could help with oculus controls

**Comment by Sorenon** [comment]
MCXR is finally published on Modrinth https://modrinth.com/mod/mcxr-core, https://modrinth.com/mod/mcxr-play the mod is still in beta but I think its stable enough to have it on there. I will also be positing this on CurseForge and creating a page for TitleWorlds soonish.
