### ISSUE TITLE
[BUG] Camera issues on pancake mode

### ISSUE THREAD

**Issue by StarHyena** [Sorenon/MCXR#75]
The camera is heavily off-center when MCXR is disabled
![image](https://user-images.githubusercontent.com/86370188/173143786-21b4d018-c2df-4ef6-acd0-dabd9daf611d.png)

**Comment by baphomutt** [comment]
Can confirm this is an issue with MCXR. 
I had it disabled and VR mode paused and my view was also tilted, specifically when I used shaders. 

I was able to get the view fixed by moving MCXR out of the mods folder after following the discussion over here: https://github.com/IrisShaders/Iris/issues/1337#issuecomment-1079818462
